name: Plugin asset/readme update
on:
  push:
    branches:
    - master
jobs:
  master:
    name: Push to master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Compile CSS
    - name: Compile CSS
      uses: gha-utilities/sass-build@v0.2.5
      with:
        source: assets/style/scss/embed-privacy.scss
        destination: assets/style/embed-privacy.css
        outputStyle: expanded
    - name: Compile CSS compressed
      uses: gha-utilities/sass-build@v0.2.5
      with:
        source: assets/style/scss/embed-privacy.scss
        destination: assets/style/embed-privacy.min.css
        outputStyle: compressed
    # Minify asset JavaScript
    - name: Minify JavaScript
      uses: nizarmah/auto-minify@v2.0
      with:
        directory: assets/js
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@master
      env:
        README_NAME: README.md
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
